### ISSUE TITLE
Screensaver remains "black" after starting

### ISSUE THREAD

**Issue by VLD-010** [JohnCoates/Aerial#1083]
iMac 2019 (i5-9600K with Radeon Pro 580X)
macOS 10.15.6
monitor: built-in 5K-Retina

This morning I upgraded from Aerial version 1.9.x to the latest version, using Aerial Companion. Now I have version 2.0.5 installed.

When the screensaver is starting, the screen remains "black" and there are no video's being displayed. No error messages are popping up. Checked my internet connection and everything is normal (online). I use a pi-hole, but that was never a problem before. Added a few new whitelist rules nonetheless (including *.apple[.]com and *.githubusercontent[.]com). 

In the setting pane, I have selected the tvOS 13 source for displaying video's (disabled the community video's in the settings pane).

What is going wrong? 

I included the logfile, FWIW. [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5145075/AerialLog.txt)

**Comment by glouel** [comment]
Hey @VLD-010 

So yes, githubusercontent is needed now, but apart from that nothing really changed, so it's a bit weird. Do you happen to use something else than the pi-hole ? No Little Snitch on top ? 

One thing that puzzles me a bit is, after upgrade, your cached videos should still be there. And it's pretty clear it's empty now. How were you using Aerial previously, did you actually stream all the time and never cache anything ? 

According to your logs, the manifests downloaded ok so that's fine:

```
2020-08-29 12:18:51.211 : source : tvOS 13 contains 90 new videos (total 90)
2020-08-29 12:18:51.211 : source : tvOS 12 contains 0 new videos (total 90)
2020-08-29 12:18:51.211 : source : tvOS 11 contains 0 new videos (total 90)
2020-08-29 12:18:51.211 : source : tvOS 10 contains 9 new videos (total 99)
```

So Aerial knows where to get your videos. 

According to your logs too, you set 4K HEVC as the video format. If you had another format, that could explain why your cache was wiped. 

So with nothing in the cache, Aerial tries a desperate streaming (which I promised was gone in 2.0.0 but is still there for this one case:

```
2020-08-29 12:18:51.214 : <AerialView: 0x7f98d4e08740> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT329_117NC_401C_1037_IRELAND_TO_ASIA_v48_HDR_PS_FINAL_20180725_F0F6300_HDR_4K_HEVC.mov
2020-08-29 12:18:51.456 : Processsing contentInformationRequest
2020-08-29 12:18:51.456 : expected content length: 220766165 type:com.apple.quicktime-movie
2020-08-29 12:18:51.462 : Processsing contentInformationRequest
2020-08-29 12:18:51.462 : expected content length: 220766165 type:com.apple.quicktime-movie
2020-08-29 12:18:51.621 : <AerialView: 0x7f98d4e08740> startAnimation frame (0.0, 0.0, 2560.0, 1440.0) bounds (0.0, 0.0, 2560.0, 1440.0)
2020-08-29 12:18:53.924 : connectionDidFinishLoading
```

So it looks like at the very least the connection gets replied to, but it seems to fail, here's what happens in your download attempts : 

```
2020-08-29 10:20:09.714 : Starting 1 streams with 343817360 each, for content length of 343817360
2020-08-29 10:20:09.715 : last stream range: {0, 343817360}
2020-08-29 10:20:09.717 : Starting download for range bytes=0-343817360
2020-08-29 10:20:09.942 : Time-out van het verzoek.
2020-08-29 10:20:15.310 : Time-out van het verzoek.
 ```

So the connections just timeout all the time. Not that I want to point to your pi-hole configuration, but I'd try with it disabled and go from there. You may also try a video url in a browser as this may help you troubleshoot, last one tried from your log : https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT329_117NC_401C_1037_IRELAND_TO_ASIA_v48_HDR_PS_FINAL_20180725_F0F6300_HDR_4K_HEVC.mov

**Comment by VLD-010** [comment]
> How were you using Aerial previously, did you actually stream all the time and never cache anything ?

Yes, I did. Wanted to prevent video's being downloaded and consume precious SSD diskspace.

> According to your logs too, you set 4K HEVC as the video format.

I also noticed this. However, I have set 4K HDR to be used, so that is strange.

> So the connections just timeout all the time. Not that I want to point to your pi-hole configuration, but I'd try with it disabled and go from there.

I disabled pi-hole, but that doesn't solve the problem.

Furthermore, I have tried to download the tvOS 13 video's. It takes a while before the first download starts, but it works. So at some point around 35 videos were downloaded and they were also displayed when the screensaver kicks in. Result is ofcourse a few gigabytes of data (the max cache setting of 5GB is being ignored). It looks like there is an issue streaming the video's.

**Comment by glouel** [comment]
> > How were you using Aerial previously, did you actually stream all the time and never cache anything ?
> 
> Yes, I did. Wanted to prevent video's being downloaded and consume precious SSD diskspace.

Ok so there might be a bug from me here, in the sense that your old settings may cause an issue and I haven't reset them.

The very quick suggestion I could give you is delete your preferences, reboot (there's weird caching at OS level), and start again from here. 
 
> I also noticed this. However, I have set 4K HDR to be used, so that is strange.

Can you double check in Settings > Advanced ? 

> > So the connections just timeout all the time. Not that I want to point to your pi-hole configuration, but I'd try with it disabled and go from there.
> 
> I disabled pi-hole, but that doesn't solve the problem.
> 
> Furthermore, I have tried to download the tvOS 13 video's. It takes a while before the first download starts, but it works. So at some point around 35 videos were downloaded and they were also displayed when the screensaver kicks in. Result is ofcourse a few gigabytes of data (the max cache setting of 5GB is being ignored). It looks like there is an issue streaming the video's.

So it downloads now? Hmm. And yeah, if you manually tell Aerial to download all, it will ignore your limit right now, I'll fix that soon sorry about that bug. But after having cached a few, does it remain black?

> This didn't work, I get an error saying the video format and MIME-type isn't supported. Must be something with the HEVC format I guess.

Can you try in Safari ? It definitely 100% works in safari. Even in HDR.

**Comment by VLD-010** [comment]
> But after having cached a few, does it remain black? I'm a bit lost here sorry.

No, I assume one of the cached video's was being played. So no black screen here.

I will now try to delete and re-install everything and go from there after a reboot.

**Comment by glouel** [comment]
Sorry if I was unclear, just delete the plist and reboot. No need to reinstall Aerial. In Catalina it's:

`~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist`

(make sure you get the path right, it's in ByHost, not a level before)

**Comment by VLD-010** [comment]
> Can you try in Safari ? It definitely 100% works in safari. Even in HDR

My mistake, I am using FF so that miht be the catch. In Safari it is working, also with pi-hole enabled.

> Sorry if I was unclear, just delete the plist and reboot.

After deleting and rebooting, nothing seems to have changed for the better. FYI, in the meantime I downloaded the community video's (all 20 of them) and if I only select this source in the setting pane, Aerial works like a charm. As soon as I select tvOS 13 or tvOS 10 as a source, without downloading all of the available video's, nothing is being displayed. So it's definately a streaming issue.

Appreciate your support!

**Comment by glouel** [comment]
Can you send me a fresh log from after your changes so I can have a look ? It's super weird, basically if you have nothing, here's what should happen:

- Aerial streams ONE video, while downloading a second
- then it plays the downloaded video if it's done, while grabbing a new one in the background, rince repeat until you reached your cache limit

Looks like downloading *from the pref panel* works for you. And streaming fails somehow, so that's weird. What it does is exactly what safari does which makes it even weirder, so definitely needs to investigate that !

**Comment by VLD-010** [comment]
Here's the latest logfile... hope it helps!

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5145205/AerialLog.txt)

**Comment by glouel** [comment]
Thanks, I'll double check something here. In the meantime, here's a suggestion, in the preference panel, press the little star on a random tvOS video. It will download (there's a progress bar that will appear next to the close button). 

Then close the panel and system preferences (makes the logs a bit easier to read), and launch the screensaver.

The one you faved should play and assuming you still have space in your cache, it will grab new ones (you may want to both raise the cache limit and enable the progress indicator in the Settings Cache just to observe if that works).

**Comment by VLD-010** [comment]
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/5145225/AerialLog.txt)

> The one you faved should play and assuming you still have space in your cache, it will grab new ones

This works indeed. I can see other files being saved in the cache folder, while the favoured video is playing.

**Comment by glouel** [comment]
So it's probably the initial streaming that is failing, I probably broke something, I'll do a fresh test and let you know. 

From here on out you should be ok, feel free to wipe your cache/reset a limit if you need, just manually fave one to get the thing started. It will slowly fill up your cache in the background and grab new videos based on what you set on the rotate thing in Settings > Cache.

**Comment by VLD-010** [comment]
> From here on out you should be ok

Thanks, I'll give a a go!

Hopefully you will be able to figure out what is going wrong. I prefer the "stream only" option to avoid using diskspace for cached videos. My internet connection speed is more than sufficient to stream the videos that are being selected.

Thanks again!

**Comment by glouel** [comment]
Yep I'll track it down, but just to clarify, streaming all the time, that's no longer possible in 2.0. I mean, sure, you can trick Aerial to do it still (assuming I fix that bug), but I strongly recommend you don't. 

I very much suggest you go with a small cache instead and roll with it.

**Comment by abhimat** [comment]
Just wanted to chime in to say that I have also been seeing the same issue as the original poster in the latest update running on Catalina, and I’m not using Little Snitch or Pi-hole, just the built in macOS Firewall. After starring videos, they start downloading, and those starred videos play fine from that point in the screen saver. That seems to suggest that the issue is occurring somewhere during the initial download while a screensaver is playing, but downloads initiated in the prefs pane when starring a video appear to work fine.

Like the original poster, I upgraded from 1.9.x, but didn’t have a cache from that earlier version as I was using stream only in that previous version.

**Comment by frankhome61** [comment]
Is there a reason why streaming is no longer an option?

**Comment by glouel** [comment]
@frankhome61 Apple servers don't really support streaming, so the results can be unreliable and it's been a support burden. Plus it's putting unneeded pressure on their CDNs.

**Comment by linuxcontainersio** [comment]
Also black screen , I downloaded all the 1080 HDR videos first and they are in the Cache directory the log file for eg says .2020-09-01 15:27:25.419 : <AerialView: 0x7fd900d0d130> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_CH_C007_C004_PSNK_v02_HDR_FINAL_20180709_HDR_2K_HEVC.mov but I can see that file in the cache directory from a few days ago

**Comment by glouel** [comment]
@linuxcontainersio did you also used to stream ?

To you and @frankhome61 I would suggest removing the preferences and starting fresh. I did check what could be the issue but can't seem to find anything. Please look here at the bottom to find the preferences file to remove, you need to reboot after deleting the file : https://aerialscreensaver.github.io/installation.html

**Comment by petersj69** [comment]
Hi, got the same, black screen after starting the screensaver, this started after updating from 1.X to version 2. If I go into settings an error message pops up:
>An error occured loading the file
>Please check your network connection, firewall, and try again. `

In the logs I can see this:

`2020-09-07 08:26:59.921 : ***Display Detection Done***`
`2020-09-07 08:26:59.921 : Using : nil`
`2020-09-07 08:26:59.921 : <AerialView: 0x7ffb93a23ec0> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)`
`2020-09-07 08:26:59.922 : Using dot workaround for video driver corruption`
`2020-09-07 08:26:59.943 : tvOS 13 is enabled`
`2020-09-07 08:26:59.944 : tvOS 12 is enabled`
`2020-09-07 08:26:59.944 : tvOS 11 is enabled`
`2020-09-07 08:26:59.944 : tvOS 10 is enabled`
`2020-09-07 08:27:00.183 : <AerialView: 0x7ffb93a23ec0> backing change 1.0 isDisabled: false frame: (0.0, 0.0, 296.0, 184.0) preview: true`
`2020-09-07 08:27:00.184 : Could not open manifest for source at https://raw.githubusercontent.com/glouel/AerialCommunity/master/`
`2020-09-07 08:27:00.184 : Could not open manifest for source at https://raw.githubusercontent.com/glouel/AerialCommunity/master/`
`

When I try to open that page I get an...

`400: Invalid request`

I tried the "reset all settings", no change.

**Comment by glouel** [comment]
@petersj69 please check this instead : https://github.com/JohnCoates/Aerial/issues/1091#issuecomment-688047752

This is a China specific issue that is hopefully fixed with the new installer

**Comment by petersj69** [comment]
@glouel I am in Switzerland... :-)
I just tried to update to 2.0.8 and the error remains...

Log now complains about

> 2020-09-07 09:20:36.386 : Could not open manifest for source at https://aerialscreensaver.github.io/community/
> 2020-09-07 09:20:36.386 : Could not open manifest for source at https://aerialscreensaver.github.io/community/

Trying to open it shows me a 404

**Comment by glouel** [comment]
Little Snitch or another firewall then ?

**Comment by petersj69** [comment]
It's a 404 from GitHub.

> 404
> 
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
> 
> Read the full documentation for more information about using GitHub Pages.
> 
> GitHub Status — @githubstatus
>

**Comment by petersj69** [comment]
True, I checked that beforehand for 2.0.7 and there was nothing complaining in LittleSnitch, now it showed up that it created a temp blocking rule. I converted that to a permanent allow and now it seems to work! Thanks!

**Comment by glouel** [comment]
Yes it's the eternal issue with little snitch. Basically they can't popup a message because screensavers run both in System Preferences, and as a full screen app, so they create a deny rule. Glad to hear it's fixed.

**Comment by burnout-syndrome** [comment]
Same issue here... Display stays black, and settings are freezing when I click on "Cache".

**Comment by glouel** [comment]
@burnout-syndrome this is all about Little Snitch. 

You need to modify the block rule it created to allow the connection to go through. You can create rules manually following this guide: https://aerialscreensaver.github.io/troubleshooting.html. You need to also add `aerialscreensaver.github.ioù to the rules you create. You can contact their support if you need help with their software.

**Comment by burnout-syndrome** [comment]
But what about freezing every time I try to open the cache-setting?
I created a new rule in Little Snitch with your settings from troubleshooting, no changes. This is the latest log:

2020-09-11 12:02:15.428 : Öffnen fehlgeschlagen
2020-09-11 12:02:15.702 : Öffnen fehlgeschlagen
2020-09-11 12:02:15.730 : Öffnen fehlgeschlagen
2020-09-11 12:02:15.732 : Öffnen fehlgeschlagen
2020-09-11 12:02:15.740 : Öffnen fehlgeschlagen
2020-09-11 12:02:15.748 : Öffnen fehlgeschlagen
2020-09-11 12:02:17.332 : sourcecallback
2020-09-11 12:02:19.344 : tvOS 13 is enabled
2020-09-11 12:02:19.353 : tvOS 12 is enabled
2020-09-11 12:02:19.354 : tvOS 11 is enabled
2020-09-11 12:02:19.355 : tvOS 10 is enabled
2020-09-11 12:02:19.670 : Refreshing video list
2020-09-11 12:02:19.671 : source : tvOS 13 contains 90 new videos (total 90)
2020-09-11 12:02:19.672 : source : tvOS 12 contains 0 new videos (total 90)
2020-09-11 12:02:19.673 : source : tvOS 11 contains 0 new videos (total 90)
2020-09-11 12:02:19.674 : source : tvOS 10 contains 9 new videos (total 99)
2020-09-11 12:02:19.675 : <AerialView: 0x7fe88b40f140> pnv
2020-09-11 12:02:19.675 : <AerialView: 0x7fe88b40f140> Setting player for all player layers in []
2020-09-11 12:02:19.700 : lsunrise 2020-09-11 03:01:17 +0000 lsunriseEnd 2020-09-11 06:01:17 +0000
2020-09-11 12:02:19.701 : psunset 2020-09-11 16:39:11 +0000 lsunset 2020-09-11 19:39:11 +0000
2020-09-11 12:02:19.702 : current 2020-09-11 10:02:19 +0000
2020-09-11 12:02:19.702 : day
2020-09-11 12:02:19.703 : remaining in plist : 0
2020-09-11 12:02:19.704 : generate playlist
2020-09-11 12:02:19.705 : playlist count: 99
2020-09-11 12:02:19.706 : Final count : 0
2020-09-11 12:02:19.707 : Empty playlist, not good !
2020-09-11 12:02:19.707 : returning random video after condition change not met !
2020-09-11 12:02:19.709 : initvideocache
2020-09-11 12:02:19.711 : <AerialView: 0x7fe88b40f140> streaming video (not fully available offline) : https://sylvan.apple.com/Videos/comp_HK_H004_C001_PSNK_DENOISE_v14_SDR_PS_FINAL_20180731_SDR_2K_AVC.mov
2020-09-11 12:02:19.712 : sourcecallback
2020-09-11 12:02:19.714 : AssetLoaderDelegate deinit
2020-09-11 12:02:22.074 : Processsing contentInformationRequest
2020-09-11 12:02:22.076 : expected content length: 619839252 type:com.apple.quicktime-movie
2020-09-11 12:02:22.080 : Processsing contentInformationRequest
2020-09-11 12:02:22.081 : expected content length: 619839252 type:com.apple.quicktime-movie
2020-09-11 12:02:22.373 : connectionDidFinishLoading

**Comment by glouel** [comment]
> But what about freezing every time I try to open the cache-setting?

Can you make a screenshot ? 

> I created a new rule in Little Snitch with your settings from troubleshooting, no changes. This is the latest log:

I suggest you make a rule allowing ALL traffic for legacyScreenSaver. Here it looks like you are not allowing traffic to sylvan.apple.com.

**Comment by burnout-syndrome** [comment]
I allowed all traffic in the rule I created, but I will check it again.

**Comment by glouel** [comment]
@burnout-syndrome what about the tiny preview, same thing ? And are you behind some corporate firewall or at home (or in China) ? I'll try to get back to you tonight.

**Comment by burnout-syndrome** [comment]
Yes, the small preview stays black, too. No, I am at home, without any other firewall. And I live in Germany. Thank you very much for your support!

**Comment by burnout-syndrome** [comment]
Just a short info, I installed version 2.0.1 yesterday evening and it works fine. But as soon as I update to version 2.0.8, I have a black display.

**Comment by glouel** [comment]
@burnout-syndrome sorry I didn't get back to you earlier, I'm a bit puzzled here, could you zip and attach your complete debug log so I can have a look ?

**Comment by burnout-syndrome** [comment]
Everything´s okay, I am sure you have a lot do to. Here you are:

[AerialLog.txt.zip](https://github.com/JohnCoates/Aerial/files/5213844/AerialLog.txt.zip)

**Comment by burnout-syndrome** [comment]
Now I am totally confused. I installed version 2.0.8 again for the log file, and suddenly the latest version also works for me, I have a picture and no longer a black display. Fixed problem, I would say carefully.

**Comment by glouel** [comment]
There are a couple of reasons that could explain this. One change I made in 2.0.8 was to download the files from aerialscreensaver.github.io instead of the old url (for compatibility with China...). It's possible 2.0.1 downloaded some missing file that was stuck by a firewall rule and now you're good to go.  

I'm a bit puzzled by your log though, were you using streaming and not caching videos in the old 1.9.X versions of Aerial ? It looks like Aerial 2 keeps streaming all the time which is NOT what should happen. Can I see your caches settings ? Would it be possible that you had unchecked "Automatically download videos" but didn't download any manually by yourself ?

**Comment by burnout-syndrome** [comment]
Well, the main thing is that it works now. Yes, I had set it up so that the videos were only streamed because I didn't have much space on my ssd. Here is a screenshot of my cache settings:

![Bildschirmfoto 2020-09-13 um 11 36 01](https://user-images.githubusercontent.com/65822359/93014971-ac7d4d00-f5b5-11ea-896a-7ea8d4066ab4.png)

And yes, I didn't download a video manually and unchecked "Automatically download videos".

**Comment by glouel** [comment]
I'm surprise it never saved a video here, it should have and you would have been stuck watching the same video again, at least that was my intent for that particular settings combination but I guess I got that one wrong. 

Glad it's fixed for you anyway ;)

**Comment by burnout-syndrome** [comment]
No, it's different videos each time :) Whatever it was, I'm glad it works again. Thank you for your support and your time!

**Comment by justinasfour04** [comment]
I'm also getting a black screen. I just installed the latest version and I do not have any firewalls installed except for the basic firewall that comes on MacOs. What do you need from me in order to help debug this issue and get aerial screen saver working?
