### ISSUE TITLE
Energy Saver Doesn't Start

### ISSUE THREAD

**Issue by sethjustin** [JohnCoates/Aerial#129]
Hey - awesome screensaver.  But I noticed when I installed on my El Capitan system that the Energy Saver doesn't kick in to turn off the monitor when this screensaver runs.  I have the saver to run after 5min of inactivity, then for the monitor to kick off after 15min.  This doesn't seem to work w/ this screensaver.

**Comment by alistairmcmillan** [comment]
@sethjustin Which version are you running? Beta 4 should fix this issue.

https://github.com/JohnCoates/Aerial/releases

**Comment by tiagratim** [comment]
I have the same issue and have beta 4. Didn't fix it for my early 2015 MBPretina.

**Comment by sethjustin** [comment]
Yep.  I have the Beta 4 release.  :/

**Comment by thr0ttles** [comment]
this is an issue for me on Sierra. my monitor ends up staying on all night long now.

**Comment by alistairmcmillan** [comment]
@thr0ttles You most likely have an older version of the screen saver. John fixed this bug a while ago. Try the latest version...

https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

@sethjustin @tiagratim Please note, if this doesn't fix the problem, you might have two copies installed. One in `/Library/Screen Savers` and one in `/Users/YOURUSERNAME/Library/Screen Savers`. Best thing to do is delete both, then install the version linked above.

Let us know how you get on.

**Comment by thr0ttles** [comment]
@alistairmcmillan I did as you said, set my display to turn off in 1 min, activated the screen saver from a hot corner, waited over a minute, display never turned off.

**Comment by glouel** [comment]
Assuming is fixed
