### ISSUE TITLE
Aerial only playing on one side-monitor- Main monitor and other side- monitor are blank- If I choose to show date and time- it shows on the main monitor- but video only plays on the right side monitor.

### ISSUE THREAD

**Issue by kmdezine** [JohnCoates/Aerial#1313]
#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: 
- [ ] macOS version: 
- [ ] Monitor setup: 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
@kmdezine which version of macOS ? This is a macOS bug that was fixed in 13.5

**Comment by kmdezine** [comment]
Starting a few months ago. Running Ventura 13.4. so will this fix with system update? I just haven't gotten around to updating yet?

**Comment by glouel** [comment]
@kmdezine yes the bug was introduced late February I think in the beta cycle of 13.3, it's finally fixed in 13.5. Should you want more information about this, check this thread, but I'm quite sure it's this issue and will fix in 13.5 : https://github.com/JohnCoates/Aerial/issues/1286

**Comment by kmdezine** [comment]
Thanks for the response! It was starting to drive me nuts... I was trying to swap monitors and recently had to relocate the system to a new location temporarily and the issue was still happening... just glad to get the beautiful scenery back to ALL 3 monitors... I even switched to another screensaver because people see this system when it is engaged, and I didn't want to explain why the imagery was only on one monitor.

Thanks Again for letting me know. I will update as soon as I get a break in the work schedule.

**Comment by kmdezine** [comment]
Updating system now!
