### ISSUE TITLE
screensaver not spanning across multiple displays

### ISSUE THREAD

**Issue by tmolter** [JohnCoates/Aerial#1407]
<img width="1144" height="696" alt="Image" src="https://github.com/user-attachments/assets/9f8e73a7-0a3b-465c-a322-2d340ab50a49" />
I have my screensaver set up to span across both of my monitors as shown in the screenshot above. However, since updating to MacOS Tahoe, this feature seems to be entirely broken. No matter what setting i change, i always get 2 separate videos playing on each monitor. I'm on an M1 Pro MBP on MacOS 26.1, and I have the latest version of Aerial (version 3.6.3) installed.

**Comment by glouel** [comment]
@tmolter Can you go into System Settings > Desktop Background > then click the Screen saver button middle top, and make sure it says "Aerial" like this in your window ? 

![Image](https://github.com/user-attachments/assets/6583cba1-3f99-4ce2-9cc0-60b42c536a54)

As far as I know spanned mode still works but I'll double check. The more likely option is that you are running the built in videos from macOS maybe ? Let's confirm that first, thanks !

**Comment by tmolter** [comment]
<img width="835" height="737" alt="Image" src="https://github.com/user-attachments/assets/859a6c44-7ede-478b-bfde-c8340c76d8b8" />
Aerial is set as my screensaver. I'm also noticing that the options button isn't actually doing anything when clicked either.

**Comment by glouel** [comment]
Latest alpha has an "advanced screen detection" mode that should resolve this on Tahoe. Make sure you read the release note before trying though : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v3.9.9a7

The drawback is there's a 1 second delay before starting as I need to "wait" for the information to be available and passed down to the screensaver, but so far it works in all the edge cases I tried that used to fail.

**Comment by 21Kingshill** [comment]
I had version A5 before and it was working until upgrdaing to MacOS 26.4.1 (25E253). Since then two independent Videos appear. 
I just downloaded and tested A7 as mentioned, but the problem remains....

However, great job - I love this screensaver!

**Comment by glouel** [comment]
> I had version A5 before and it was working until upgrdaing to MacOS 26.4.1 (25E253). Since then two independent Videos appear. I just downloaded and tested A7 as mentioned, but the problem remains....
> 
> However, great job - I love this screensaver!

Try the latest, there's auto updates now too, it makes it easier to follow. That said, the auto download is broken so if you want more videos, you'll have to download videos manually for now, it should be fixed soon though. Use 3rd icon at the bottom of the menu to open the library and pick a few to download :

![Image](https://github.com/user-attachments/assets/ff7a0789-bfc4-4ebf-a9e0-15912466b5b6)

Latest release is here : https://github.com/AerialScreensaver/Aerial/releases (a25 as I'm writing this)

**Comment by 21Kingshill** [comment]
Initially, I had the same issue again. After a clean install it now works perfectly again.
Thanks a lot
