### ISSUE TITLE
Graphical glitches in beta and GM macOS High Sierra 10.13

### ISSUE THREAD

**Issue by ultiferrago** [JohnCoates/Aerial#377]
Had successfully running on Sierra, updated to High Sierra beta and screen saver no longer works. Will load up but images appears distorted. You can tell movement is occurring in the background, but the image itself does not correctly display. Attempted to uninstall and reinstall to no avail. Checked the logs and do not see any errors that have to do with the screen saver 

I attempted taking a screenshot of the distortion so that you could see what I mean and the screen shot actually shows the correct image. 

The image is displayed correctly very briefly prior to the image being distorted. It appears that when the image starts moving is when the distortion occurs. 

Disabling automatic graphic switching prevents the issue from occurring. This was not the case prior to High Sierra.

**Comment by ultiferrago** [comment]
I attempted taking a screenshot of the distortion so that you could see what I mean and the screen shot actually shows the correct image.

**Comment by affrae** [comment]
I just want to add 👍 to @ultiferrago's 👆 comment.

To me it looks like the frames are playing out of order - or the video is being rendered twice?

👾 💜

**Comment by alistairmcmillan** [comment]
Duplicate of #365  .

They are rewriting the window manager to use Metal 2, so graphical glitches are to be expected while this work is ongoing. But please please please report these issues to Apple using the Feedback app.

**Comment by sn0wyfall** [comment]
I was having problems with the videos playing weirdly too!

**Comment by affrae** [comment]
Thanks, @alistairmcmillan!!

👾 💜

**Comment by fgladu** [comment]
I have witness the problem on a 16:10 display (MacBook Air MID 2013) but not on a 16:9 display (Mac Mini MID 2011 attached to a HD TV). Both running 10.13 GM. Hope it helps narrow it down.

**Comment by mhyatt18** [comment]
It is work on High Sierra for me on my iMac Retina and on a 2015 MacBook Pro. It is not working on a brand new MacBook Pro with Touch Bar.

**Comment by jbozanowski** [comment]
On my MacBook Pro (13-inch, Late 2016, Two Thunderbolt 3 ports) - the non-touchbar version - it generally works, but right at the start of the screensaver it appears to start frozen for a split second, then flicker as if it would try to rescale, then start playing normally (at what I believe is the correct aspect ratio). For what it's worth this is tested on internal screen only, running the new default resolution of what looks like 1440x900. Running the GM - `10.13 Beta (17A360a)`.

**Comment by alistairmcmillan** [comment]
@sn0wyfall @affrae @fgladu @mhyatt18 @jbozanowski I hope you're all using the Feedback app to report this to Apple. Not sure if there is much that John can do about glitches that Apple have introduced into their own drivers or frameworks.

**Comment by affrae** [comment]
Hi @alistairmcmillan I sure have. I can also report that with the GM of High Sierra the problem appears to have disappeared for me.

However that should not also preclude reporting here as sometimes software can break across upgrades. The number of apps updated shortly after a new OS release that list changes as "Now compatible with New Version of OS" or "Fix Issues with New Version of OS" are testament to that.

By notifying here as well as with Apple, the best chance exists for the right person to identify the issue. I did not assume the problem was with Aerial, or with Apple. I just reported on both fronts.

👾 💜

**Comment by garrisoncarter** [comment]
I can confirm I have the same issue on my 2017 15in Touchbar MBP with the High Sierra GM only when running integrated graphics. Switching to discrete graphics works, and is my current work around.

**Comment by mhyatt18** [comment]
What do you mean by “discrete graphics”?

**Comment by mayhew1955** [comment]
I can confirm that using discrete graphics works as a workaround on my 2017 15in Touchbar MBP.
By discrete graphics we mean the Radeon Pro chipset.  The MBP switches automatically to the Intel HD Graphics chipset to save power and only turns on the Radeon Pro when it detects that it's needed.

**Comment by tempusthales** [comment]
The screen saver stopped working when I installed macOS High Sierra 10.13.0, on my Mac Pro Late 2013.  The screensaver floats the message "You cannot use the Aerial screen saver with this version of macOS.  Please contact the vendor to get a newer version of the screen saver."

**Comment by aamck** [comment]
Getting this issue as well on my mid 2015 15" mbp using integrated graphics - discrete chip works fine.

**Comment by curtisko** [comment]
I have a 2017 MBP 13" w/o discreet graphics and I am encountering this issue

**Comment by tjkohli** [comment]
Never used High Sierra beta, just updated to High Sierra public release on a 15" MacBook Pro 2017 and this screensaver doesn't work. Whenever it's triggered, it gives the same glitchy effect you see when you have GPU issues.

**Comment by AmisadaiGlez** [comment]
I have the same problem when I play Final Fantasy XIV or War Thunder in my MacBook Pro 13" 2016 without Touch Bar at the release version of macOS High Sierra.

**Comment by vuklau** [comment]
Also having flickering issues on my MacBook Pro 15" Mid2015 model after updating to HS

**Comment by christopher-wong** [comment]
I'm having the issue with MacBook Pro 15" Touch Bar 2017 - talked to Apple support and they don't seem to have a real solution yet. Turing off Automatic Graphics Switching does make the issue appear less often though.

**Comment by thisisjohnny** [comment]
Adding my stats here to potentially help debugging. I am having this flickering issue on my MacBook Pro (Retina, 13-inch, Early 2015)
**Processor** 3.1 GHz Intel Core i7
**Memory** 16 GB 1867 MHz DDR3
**Graphics** Intel Iris Graphics 6100 1536 MB

**Comment by creativitydifferent** [comment]
adding my specs and some more context...
I have a MacBook Pro w/Touchbar (13-inch, 2017)
when connected to a Samsung 23.5-inch monitor, the Aerial videos work fine (on both screens)
but without the external monitor connected, the video is distorted as described above.
This started happening after upgrading to High Sierra.

**Comment by eddeemurfy** [comment]
Same issues here on a Macbook 13 inch 2014 after the update to HS

**Comment by tlaak** [comment]
Having similar issues on my 15" mid 2017 MBP. Switching the integrated Intel Iris graphics card off helped.

**Comment by gricha2380** [comment]
I'm also seeing the issue on a 13" Retina MBP Early 2015 and 15" Retina MBP 2013. However, I suspect the graphic flickers are a general High Sierra issue rather than specific to Arial.

**Comment by drewwilliams** [comment]
Also seeing this on my MacBook Pro touch Bar (15-inch, 2017) running High Sierra (10.13 17A365) when trying to view on the built-in display. Worked fine when connected to external display, but think that the issue is battery vs. power supply. Turning off Settings > Energy Saver > Automatic graphics switching allows the screensaver to work fine.

**Comment by aanttila** [comment]
I've read through this thread twice, and I don't see a referenced Radar with Apple for High Sierra GM--am I missing it?  Are we sure it's an Apple bug, and not a problem with how Aerial works?

**Comment by AsydRayn** [comment]
Here's what it looks like on my MBP 2017.

![img_20171001_100026](https://user-images.githubusercontent.com/32578033/31289949-b9c087b8-aa98-11e7-8753-511ca44086e6.jpg)

**Comment by Stevenfly** [comment]
@AsydRayn I have exactly the same screen like your photo. I also posted an issue (closed due to replicate of this thread) #398

**Comment by AsydRayn** [comment]
@mayhew1955 Oddly, I don't have any of those options under "energy saver" on my MBP w/TB 2017. Under Displays setting, I have Default or Scaled.

> You can force the MBP to use the Radeon Pro chipset in the Energy Saver panel in Settings.

**Comment by creativitydifferent** [comment]
apparently these options aren’t available on a 13” MBP. it doesn’t come with the alt chipset

**Comment by vicchi** [comment]
Just to confirm @drewwilliams' comment, on a 15" 2017 MacBook Pro running High Sierra 10.13, de-selecting "Automatic graphics switching" in System Preferences Energy Saver allows video playback in Aerial without problem. Re-enabling this setting and the graphics glitching returns.

**Comment by darknater** [comment]
It appears the new supplemental high Sierra update that just dropped fixed the issue on my MBP15" in integrated gfx mode.

**Comment by jackhcurtis** [comment]
Having the same issue on my 2017 13" MacBook Pro w TouchBar. It works fine on my 27" 4K Monitor. Do we know this happens on the internal display but not on an external?

**Comment by vicchi** [comment]
@jackhcurtis For me it's limited to the internal display; works fine on external displays.

**Comment by pytrisss** [comment]
Yeah, with external it works. Macbook 12inch 2017. Worked fine on the same OS version with 2015 macbook I think.
BTW the workaround "show with clock" works, but of course - it's with clock :)

**Comment by mayhew1955** [comment]
Thanks for the workaround "show with clock", it's better than nothing !

**Comment by mondher** [comment]
I have two MBP 15" with touchbar.. aerial is not working on the more recent one. Both have automatic graphics switching checked in the settings/energy saver stop screen.. I wonder whether this issue I am experiencing only on the latest MBP is due to differences in graphics cards..
The one that has no issue has Intel HD Graphics 530 (24-Bit Color).. the latest MBP has Intel HD Graphics 630 (30-Bit Color)

**Comment by controversial** [comment]
I have a 2017 Macbook Pro 13" without touch bar; I consistently see the same screen as @AsydRayn. Graphics switching isn't an option in my Energy Saver preferences, so I don't know how to fix. I'm on the latest versions of Arial and of High Sierra.

**Comment by AsydRayn** [comment]
@Luke, there is no fix yet. But you can get it to work by turning on the clock.

On Oct 11, 2017, at 9:36 PM, Luke Deen Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a 2017 Macbook Pro 13" without touch bar; I consistently see the same screen as @AsydRayn<https://github.com/asydrayn>. Graphics switching isn't an option in my Energy Saver preferences, so I don't know how to fix. I'm on the latest versions of Arial and of High Sierra.

**Comment by tjkohli** [comment]
Do you think this has to do with Metal 1 vs Metal 2? If so, a rewrite/recompile might be needed.

**Comment by cybermaster69** [comment]
i have the same problem MacBook Pro 13.

**Comment by AsydRayn** [comment]
I'm curious how this works when the clock is enabled, yet it won't work when not. If it's a driver issue what is it that the clock toggle "patches" to make it work.

**Comment by cybermaster69** [comment]
any update yet?

**Comment by sagitt** [comment]
there are another problem like this even it works... when going back to desktop if the macbook are closed with an external montor

**Comment by alistairmcmillan** [comment]
Installing 10.13.1 seems to have fixed the problem for me. Is anyone still getting the glitches with 10.13.1 installed?

**Comment by Stevenfly** [comment]
@alistairmcmillan Nope, mine still has the same picture as @AsydRayn posted, with 10.13.1 installed :(

**Comment by sagitt** [comment]
10.13.1 but same problem

**Comment by controversial** [comment]
I still have this problem on 10.13.1

**Comment by Rand01ph** [comment]
I still have this problem on 10.13.1
rMBP2017 with Touch Bar

**Comment by v8c3** [comment]
I'm having this problem, 15" touchbar MBP 2017 running 10.13.1. It's solved with discrete graphics mode.

**Comment by mastershaig** [comment]
Same screensaver problem on MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by liuliangsir** [comment]
same here: MacBook Pro (Retina, 13-inch, Early 2015) macOS High Sierra(10.13.1)

**Comment by lparry** [comment]
same problem on a 2017 macbook pro 13", high sierra 10.13.1. Strangely it works fine on all displays clock-free if any external display is connected, but looks like the display is dead if it's showing only on the internal display. Displaying the clock with just the internal display also works fine for whatever reason

**Comment by Telenova1919** [comment]
I'm running 10.13.1 macOS High Sierra on my MacBook Pro 17" with 2.8 GHz Intel Core 17 Processor and, following ultiferrago's suggestion, the graphical glitches I was getting in Safari (extreme pixellation, negative imaging on at least one e-newspaper site), I disabled Automatic Graphics Switching in Energy Saver in Preferences, and issues seems to be resolved.

**Comment by BenjaminSouchet** [comment]
Thanks @ultiferrago, disabling "Automatic graphic switching" prevents the issue from occurring.
<img width="740" alt="solution" src="https://user-images.githubusercontent.com/17025808/32702219-ec269af4-c7e3-11e7-8e96-675ca1e6b0d7.png">

I'm on High Sierra (version 10.13.1), MacBook Pro 15" 2017

**Comment by atdr** [comment]
I'm experiencing the same issue. [Here's a rubbish video](https://youtu.be/qriMzde3uoU).

10.13.1 on MacBook Pro (15-inch, 2017)

When notifications appear, the image returns to normal before breaking again as soon as the notification disappears.

**Comment by sagitt** [comment]
Please test it on external display, it works on my mbp 13 with touchbar but when touch the mouse with closed display but external monitor I see glitches running

**Comment by jbweb** [comment]
Same issue here on my MacBook Pro 2015. It seems related to the camera, as it only glitches when someone moves in front of the camera

**Comment by phosphatstange** [comment]
Same issue here. MacBook (Retina, 12-inch, 2017), 8 GB 1867 MHz LPDDR3, 1,3 GHz Intel Core i5,  Intel HD Graphics 615 1536 MB running MaOS High Sierra (10.13.1 (17B48)) - with clock toggle it works.

**Comment by mountaineer20** [comment]
I observed that when I was working to document this bug using Quicktime to perform a screen capture appears to also resolve the issue. Anytime I was running a screen capture Aerial played back great. When I was not running a screen capture I ran into the same described interlacing issue.

**Comment by mpede** [comment]
Hi folks, 
just wanted to add to the thread how my MacBook Pro w/ touch bar is behaving
 after upgrading to High Sierra. At first I got the same scrambled screen shown earlier in this thread by @AsydRayn 
After forcing discrete graphics I get a static image from the video forever, nothing moving. Now switching back to integrated graphics (monitored by gfxCardStatus helper) I don't get the scrambled screen anymore but the static image as well. Not sure if this helps - hope this can be fixed soon as I love this screensaver! Thanks
![about_this_mac](https://user-images.githubusercontent.com/4440614/34735335-63c7f43c-f56f-11e7-8729-87829520f5b7.jpg)
!

**Comment by whaaa** [comment]
Hi Ryan just a note on the previous comment to help clarify things though it’s not my comment: on 13.2 about this mac no longer shows the Radeon card, so there is a good chance the guy’s computer does have a discrete graphics card. Cheers!

**Comment by hardcore** [comment]
Same here.

<img width="332" alt="bildschirmfoto 2018-01-17 um 12 22 10" src="https://user-images.githubusercontent.com/58683/35040353-1290b7f8-fb81-11e7-8cb5-36d9f8759787.png">

**Comment by thomas-alrek** [comment]
+1

**Comment by darkobits** [comment]
This is an ongoing issue in High Sierra. I hope a fix is forthcoming!

**Comment by lawonga** [comment]
Me too!

**Comment by ahmedelshinnawy** [comment]
same issue , its not fixed yet on latest HS 10.13.3

**Comment by zacdavies** [comment]
Confirmed issue still appearing on 10.13.3. Using a 2017 Macbook, so no option to change graphics chipset.

**Comment by buzzb0x** [comment]
Is it me or turns out I fixed it by enabling "Show with clock" in the screen saver settings?

*Config: 
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
macOS High Sierra 10.13.3*

**Comment by BenjaminSouchet** [comment]
@buzzb0x : Yes, when you enabling "Show with clock" this prevent you macbook to switch from your graphic card to the Intel HD Graphics. If you don't want the clock on your screensaver just disable "Automatic graphic switching" on your macbook settings ("Energy Saver" tab)
![image](https://user-images.githubusercontent.com/17025808/36901290-fbcf8616-1e26-11e8-9746-f56a1d21dbbd.png)

**Comment by draupnir45** [comment]
I found some weird behavior. When I only use internal display of my MBP 13 2017, It glitches. but when I use my iMac as target display mode, It's working. even in MBP display. Hope this will helps for fixing issues..

**Comment by gwynnebaer** [comment]
I have a MacBook Pro 13" (MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) with integrated graphics, running 10.13.3. Enabling the clock feature results i smooth video; without the clock option, I get the zigzag garbled video. So for me this is a workaround for the moment as also noticed by @buzzb0x

**Comment by mustafasezgin** [comment]
2017 MBP with touch bar. Showing clock also fixes the problem for me. I do think though this might be a problem with the hardware and not necessarily the software. Im going to head into an apple store and show them this thread. I actually already had the display replaced because of this issue but it seems its still happening to me.

**Comment by robert-cody** [comment]
There is no such a problem on earlier macOS versions, so it's definitely software problem.

**Comment by mustafasezgin** [comment]
Ah ok. Didnt noticed that in this thread. Ill go over it again, thanks.

**Comment by diranged** [comment]
Didn't read the whole thread - but I have a brand new Macbook Pro 13" 2017 model, and the issue is reproducible as long as I _don't_ select `Show with clock`. If I _do_ select that setting, the screensaver works fine. There is only integrated graphics on this laptop as well, no discrete chip.

**Comment by ttyS0** [comment]
It looks like this is resolved with 10.13.4. I just updated, and tried the screen saver, removing the `show with clock` option, and after an initial video stutter the playback is smooth.

**Comment by newtonuk** [comment]
Mine isn't :-(

**Comment by ttyS0** [comment]
I suppose I should mention that my hardware is `MacBookPro14,3 w/ Intel HD Graphics 630 & Radeon Pro 560`. (i.e. MBP 15" 2017 w/TouchBar)

**Comment by gwynnebaer** [comment]
I can also confirm that the clock workaround is no longer needed for my setup with 10.13.4:
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
Intel Iris Plus Graphics 650 1536 MB

**Comment by newtonuk** [comment]
Just noticed that when I received a notification about a received email, the screensaver started playing correctly, but as soon as the notification faded it distorted again.

**Comment by drewwilliams** [comment]
This has resolved for me with 10.13.4 on a MacBook Pro Touch Bar (15-inch, 2017).

**Comment by AsydRayn** [comment]
@gwynnebaer I have the same setup as you and it's still not fixed for me when I untick clock. @newtonuk, your experience is exactly the same as mine...clock unticked, I get screen scramble until a notification arrives. Once the notification disappears, it's back to the garbled screen again.

**Comment by owellsjr** [comment]
While macOS 10.13.4 may have resolved this issue for those of you using a MacBook **Pro** it is definitely still crashing on my new 2017 MacBook. Interestingly enough, it was never an issue on my 2015 MacBook that was running the screen saver on the same version of macOS.

**Comment by owellsjr** [comment]
This issue was resolved for my 2017 MacBook in the macOS 10.13.5 public beta. I no longer have to use the "Show with clock" option to get the screen saver to work.

**Comment by gsbernstein** [comment]
Still a problem for me with 10.13.4 when "show with clock" is off or integrated graphics is on. I'm getting the version with a cropped, zoomed in central video and a second zoomed-out copy playing behind it, visible above and below.

**Comment by atdr** [comment]
I'm getting a horizontally-stretched version of the video flickering across the screen **whilst the brightness of the monitor changes**—at all other times it's back to normal in 10.13.4.

[Another rubbish video](https://youtu.be/nfVaVG7xNEs). Auto-brightness response triggered with a torch.

**Comment by El-Capitan** [comment]
OSX 10.13.4, 15" 2017 MBP (w/touch bar)
Issue resolves by disabling graphics switching in energy saver settings.
Issue appears to be with integrated graphics solution (drivers?! what is this, a PC?), but not with the discrete graphics chip on systems w/touch bar.
I do not have this issue on my other MBP (13" 2015) or Air (2015).

**Comment by DominikHoffmann** [comment]
I have a 2017 15-in MacBook Pro. I see the same scrambled images and have now twice seen spontaneous reboots, which I attribute to Aerial.

**Comment by controversial** [comment]
Fixed in Mojave Developer Beta 6 for me

**Comment by AsydRayn** [comment]
Works for me in this iteration, even without the clock, on a 2017 13" MB Pro w/Touchpad that doesn't have an "automatic graphics switching" option.

**Comment by liuliangsir** [comment]
Fixed in macOS Mojave 10.14 Beta (18A353d)

**Comment by glouel** [comment]
So this is the same as https://github.com/JohnCoates/Aerial/issues/487, I'll close this one and keep the other one open. 

Afaik Mojave fixes those issues, and our version 1.4 may fix the issue with 10.13 with the new show description option.
