### ISSUE TITLE
Not Working with MacOS 10.13.6

### ISSUE THREAD

**Issue by fahadsgalaxy** [JohnCoates/Aerial#487]
Just installed the app and it says "cannot use with this version of MacOS"

Any update coming ?

**Comment by alistairmcmillan** [comment]
It's a bug in macOS.

- Select Aerial
- Close System Preferences
- Reopen System Preferences

Does the preview work now?

**Comment by crts-failure** [comment]
the preview works but in normal mode, the screensaver crashes after a few minutes. hope a fix is in the pipeline soon. love this screensaver..

**Comment by pangao1990** [comment]
一样的问题，同求答案

**Comment by carter3d** [comment]
Same problem.  crashes after a few seconds on 10.13.6

**Comment by asvrada** [comment]
10.13.6 user here. The preview doesn't work after restart.

**Comment by alistairmcmillan** [comment]
@crts-failure @carter3d What do you mean when you say it crashes? Do you get an error message?

**Comment by crts-failure** [comment]
No error codes, the video freezes- which isn’t ideal considering it’s a screensaver. 

I initially had problems with how the video was being displayed, as in some sort of rendering or graphics issue (the video was pixelated and enlarged) but turning on the clock fixed this. Only to later discover it hangs after some time.

**Comment by alistairmcmillan** [comment]
@crts-failure Thanks. So are you running the latest version? Do you have the videos cached? Are you behind a corporate firewall or anything like that?

**Comment by carter3d** [comment]
When it crashes, my screen looks like the attached image.  But, after further testing, this only seems to occur when using the default resolution on my 13-inch, 2017 MacBook Pro and the built-in display.  When I connect to my Thunderbolt display (via a dock) at 2560x1440 resolution, the screen save runs fine.
![img_0427](https://user-images.githubusercontent.com/12088157/45318749-119b9500-b4fb-11e8-9cbe-4c478ab1162b.JPG)

**Comment by carter3d** [comment]
As for the other questions, I removed the previous version and installed the latest from Git on Saturday.  Not sure if videos are cached or not (how do I check?), and not behind a firewall that I know of.  Like I said, it seems to work fine on the same system when using a different display.

**Comment by alistairmcmillan** [comment]
@carter3d If you tick the "Show with clock" option does that clear up the corruption?

**Comment by crts-failure** [comment]
@alistairmcmillian im running this on my home pc so no corporate firewall. Tried removing and reinstalling, caching videos but no joy. It was running fine in the past so I suspect macOS update caused the corruption. I never got the garbled screen @carter3d did. I’m running at full res on a retina MacBook.

**Comment by carter3d** [comment]
show with clock seems to solve the issue

**Comment by crts-failure** [comment]
@carter3d have you left the screensaver running for a few minutes to see whether you have the same issues as I have? (Screen freeze)

**Comment by adminjwilson** [comment]
Wow, "Show with Clock" solved my dual display resolution issue!

**Comment by crts-failure** [comment]
Yes, all the video files are cached but I still find the videos freeze after a few minutes of it running.

**Comment by carter3d** [comment]
@crts-failure , I have not let the screensaver for more than a few minutes (when it isn't working).  When it is working, I don't have any issues, even after long periods of time.

**Comment by kerstin** [comment]
I've also been having problems with Aerial ever since I updated to MacOS 10.13.6 (months ago, admittedly).

It _works_, but jerkily/with flickers. The videos will play, but every few seconds it looks like they are... imploding, for lack of a better description. The image on-screen gets "sucked toward the centre" of the monitor, then will go back to fullsize, rinse repeat.

I downloaded and installed the newest version of Aerial - no idea which version I'd had installed so far - and the problem persists.

**Comment by alistairmcmillan** [comment]
@kerstin What happens if you tick the “Show with clock” option? Does that help?

**Comment by kerstin** [comment]
@alistairmcmillan With the clock added, the issue is indeed gone. Is this just a temporary workaround or will users with that OS version have to keep the clock around?

**Comment by alistairmcmillan** [comment]
@kerstin It's been this way since the release of High Sierra in September last year. Apple re-wrote the display server that draws everything to the screen and introduced this bug then. I'm not sure if its fixed in Mojave, maybe someone else can confirm that.

**Comment by kerstin** [comment]
@alistairmcmillan I upgraded not too long ago, so not looking to upgrade again all too soon. (: I think I was more wondering if it would be possible to replicate whatever the clock contributes to fix the issue (but in the form of, say, a transparent overlay, or hidden pixel or similar).

**Comment by glouel** [comment]
@kerstin can you check version 1.4 if things have improved ?

**Comment by glouel** [comment]
As far as I know this is fixed in 1.4.1

**Comment by kerstin** [comment]
@glouel I just tried it - seems to work fine now, thank you! Interestingly, the problem is still present when _previewing_ the screensaver, however. Just thought I'd mention it.

**Comment by glouel** [comment]
@kerstin thanks for checking it ! When you mean preview, you mean press the preview button in System Preferences > Screensaver ? As far as I know, this just launches the screensaver so this may not totally be fixed !

This seems to look **a lot** like that other issue here https://github.com/JohnCoates/Aerial/issues/442, are you still on 10.13.6 (not mojave) with a recent Macbook Pro ? 

That seems to be the configuration that has issues. I'm starting to blame the 10.13.6 AMD driver at this point ;) Please let me know if you keep seeing it in normal usage.

**Comment by kerstin** [comment]
Sure thing! And yeah, I meant the preview one gets to see when one clicks the preview button.

I'm on High Sierra (10.13.6) with a not super recent (several years old) MacBook Air (so no Retina display) with the default resolution and not using multiple displays, though I could try using multi displays if that might help with narrowing down the problem.

**Comment by glouel** [comment]
Are you getting a black screen in preview ? This might be a different bug, see 
https://github.com/JohnCoates/Aerial/issues/548

**Comment by kerstin** [comment]
No, the preview shows the screensaver normally, but with the bug. I tried it again now, had to wait a few seconds to see the images distorted (yesterday it happened immediately) but the problem is still there, in the preview.

I watched the _actual_ screensaver for a good 2 minutes? without anything happening, so assumed it was fine (when it was buggy, you'd see the distortions happening every few seconds). But I'll try to have an eye on it and report back.

**Comment by glouel** [comment]
Ok thank you very much, I'm reopening this to better track this ! Please report if you see in normal usage !

**Comment by glouel** [comment]
Preview had some unpredictible side effects in previous builds, also found a couple other bugs, but not sure if they are related. Here's a test build if you feel like giving it a shot : 
https://github.com/glouel/Aerial/releases/download/v1.4.2test4/Aerial.saver.zip

The distortion stuff may be 10.13.6 bug with the AMD drivers though (a lot seem fixed in Mojave per https://github.com/JohnCoates/Aerial/issues/472#issuecomment-430992470 although that may not be helpful to you).

**Comment by andsoitgoes** [comment]
Thank you!! That worked perfectly, it's running on a very old (early 2011) macbook pro with the discrete card disabled, thank you so much for that most recent one! you're the best!!

Also, is there any way you could hook into f.lux to determine the sunset/sunrise times? That would be dope :)

**Comment by glouel** [comment]
Good to hear ! 

Regarding f.lux, I don't think  they have an API for this sadly, I tried looking for one but it doesn't look like they have one :( It's possible to calculate precisely those based on lat/long, maybe I'll add that at some point as a fallback for Macs without nightshift support if I can.

**Comment by glouel** [comment]
https://github.com/ceek/solar this looks like a good option for manually calculating them. 

There's also a free (?) Yahoo Weather API I think which may be easier to use.

**Comment by kerstin** [comment]
For me, the latest version (v1.4.2test4) reintroduced the twitching of the screensaver (it continued to be present in the preview too). I've now downgraded to v1.4 again.

**Comment by glouel** [comment]
> For me, the latest version (v1.4.2test4) reintroduced the twitching of the screensaver (it continued to be present in the preview too). I've now downgraded to v1.4 again.

Looks like my message to you yesterday was lost in the github bugs. 1.4.2test4 still had some pretty bad issues. I've fixed many things since in 1.4.2, maybe give it a shot : 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.2/Aerial.saver.zip

**Comment by glouel** [comment]
> Thank you!! That worked perfectly, it's running on a very old (early 2011) macbook pro with the discrete card disabled, thank you so much for that most recent one! you're the best!!
> 
> Also, is there any way you could hook into f.lux to determine the sunset/sunrise times? That would be dope :)

So as a workaround for machines without night shift, I started adding a manual calculation from coordinates, if you want to give it a shot try 
https://github.com/glouel/Aerial/releases/download/v1.4.4test2/Aerial.saver.zip

There's a new mode in "Time" panel where you can enter your coordinates and it will calculate sunrise/set automatically for you.

**Comment by glouel** [comment]
@andsoitgoes Give 1.4.4 a try, final build was posted with a proper fallback for machines that don't handle night shift.

**Comment by glouel** [comment]
@keikoro if you are interested we now have a fix that seem 100% for that video driver issue in beta 3, as reported by other users. 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta3/Aerial.saver.zip

**Comment by keikoro** [comment]
@glouel I downloaded it and it really seems to be fixing everything - thank you, much appreciated!

**Comment by glouel** [comment]
Glad I finally got it 🎉🎉🎉
