### ISSUE TITLE
iMac, external monitor - inconsistent playback

### ISSUE THREAD

**Issue by WebVeteran** [JohnCoates/Aerial#530]
I have a 27" iMac with an external 1080p display. All videos are cached.

The external display shows videos every time. It looks like the 4K files. They are super crisp(er than normal), with smoother motion and less mpeg artifacts.

But the main screen only some times plays videos. And they seem to be the 1080p version - motion not as smooth and I see mpeg artifacts.

I would assume the opposite would happen because the external screen is 1080p and the internal screen has much higher resolution (but under 4k still).

In case this is a 4K issue, can you add an option to show the file name or other details - in addition to the "Show descriptions" option?

![image](https://user-images.githubusercontent.com/40175/46845810-0d3cf300-cdab-11e8-8b4b-c4a7b4a3e7df.png)

**Comment by glouel** [comment]
As you can see on  the left column, not every video is available in 4K. Only those with the "4K" label are, the oldest ones are 1080p H.264 only and you have those selected too for playback.

If you strictly only want 4K, you'll have to disable the old videos. Click the action button below the list and click the "Check only 4K", this way you'll have what you expect. 

You can check for  yourself the old files by going to the "Cache" tab and click "Show in Finder", this will show you the videos and you can open them in quicktime. You'll see that on a 5K display, some can be extremely blocky indeed.

**Comment by WebVeteran** [comment]
I now have only 4K videos selected on the left. And Preferred = 4K. Sometimes the main display shows a video. Sometimes it does not.

I've noticed that when the internal monitor (on the right) does not display a video, the external monitor (on the left) also does not display the video name. See attached.

Maybe different options are in order:

The checkbox **Play different Aerial on each display** becomes a select "**Play Aerials**":
- Only on main display
- Mirrored on every display
- Independently on each display

Then the options w/in **Show Descriptions**:
- 10 Seconds
- Always
- Debug (output the file name, codec, dimensions, etc)

![image](https://user-images.githubusercontent.com/40175/46874366-fd52fc80-ce06-11e8-9eb6-7b3f658566b3.png)

![screen shot 2018-10-12 at 10 12 29 am](https://user-images.githubusercontent.com/40175/46874527-591d8580-ce07-11e8-9906-6df96ca82164.png)

I'm a web developer so I don't know the coding involved in native apps. Otherwise I'd make pull requests. Thank you for this awesome Screensaver!

**Comment by glouel** [comment]
> I now have only 4K videos selected on the left. And Preferred = 4K. 

Good !

> Sometimes the main display shows a video. Sometimes it does not.

Not good, that's a bug.

> I've noticed that when the internal monitor (on the right) does not display a video, the external monitor (on the left) also does not display the video name. See attached.

Intriguing. A few things if you may : 
- Can you tell me which version of MacOS you are running ?
- Also, can you possibly disable the "show clock" option, see if that somehow fixes the problem ? (long shot but we've seen weird things !)
- Do you see the same issue when you have "Play different Aerial on each display" checked ?

> Maybe different options are in order:
> 
> The checkbox **Play different Aerial on each display** becomes a select "**Play Aerials**":
> 
> * Only on main display
> * Mirrored on every display
> * Independently on each display

Yep, main screen only is on my todo list. But by default, it should mirror. 

> Then the options w/in **Show Descriptions**:
> 
> * 10 Seconds
> * Always
> * Debug (output the file name, codec, dimensions, etc)

We probably need a debug option somewhere yep ! Right now I'm working on the network debug but I'll try to think about this one. 

> I'm a web developer so I don't know the coding involved in native apps. Otherwise I'd make pull requests. Thank you for this awesome Screensaver!

Thanks for your report ! Please let me know about the stuff above so hopefully we can fix that.

**Comment by glouel** [comment]
Follow up, did a quick testing : 
- On my iMac 5K (Late 2015), running Mojave, and an external screen (1280x800) : Always OK
- On my Macbook Air (2011), running 10.13.6, same external screen (1280x800) : I reproduce your bug
- On my Macbook Air (2011), running 10.13.6, larger external screen (1920x1200) : I reproduce your bug

Can you confirm you're running 10.13.6 ? I'm afraid this may be one of these video driver issues that's out of our control. Same goes for so many of the scale bugs, wrong ratio, black bars that comes and goes with new video drivers.

**Comment by WebVeteran** [comment]
Earlier the video name was showing on both screens. Now just the internal screen - but only if the movie plays.

I disabled the clock (and them also the video title) but that made no difference.

"Play different Aerial on each display" gives odd results. Once it played on the internal only, and at like 1 frame per 3 seconds. Another time it played on the external screen only, smoothly, and with the video title on the external screen. 🤷‍♂️ 

Perhaps these are all manifestations video card resource issues. That's why I was hoping for a "main display only" option.

10.13.6, Late 2011 iMac 27", 1080p external screen.
I maxed everything out when I bought it, so the specs are pretty decent though starting to age...
  Model Name:	iMac
  Model Identifier:	iMac12,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	IM121.004F.B00
  SMC Version (system):	1.72f2

**Comment by glouel** [comment]
Are you sure you got the name on both screens in mirror mode ? Or with play different checked ? Sorry to insist but that might be important ! 

Noted for the clock and your Mac info, thanks. As far as I know on your iMac, it should be using Intel QuickSync to decode (so pretty close to what happens on my Macbook Air of the same year, Sandy Bridge generation).

I'm adding a Main display only option right now, I'll ping you back with a beta.

**Comment by WebVeteran** [comment]
Yes, the name _was_ appearing on both screens in mirror mode. But that seems to have stopped now.

**Comment by glouel** [comment]
@WebVeteran please try this build for "main display only" mode : 
https://github.com/glouel/Aerial/releases/download/1.41test1/Aerial.saver.zip

And let me know how it goes ?

**Comment by WebVeteran** [comment]
Installed and works very well! I used a hot corner to test it over 10 times and it never failed once - Main display only, always show title, prefer 4K, only 4K videos selected.

Sometimes the framerate drops just slightly then picks up again. But I was expecting that with an older iMac. The display is still beautiful though!

It's weird how the clock is an option outside of each screen saver. It takes no visual style into account.

**Comment by glouel** [comment]
Ok great ! I'll keep looking for the other bug to see if that's on my changes or not.

Regarding framerate, 4K HEVC is fully CPU decoded on your Mac so that's definitely expected. Transcoding the 4K videos to H.264 with x264/Handbrake would significantly lower the load in your specific case.

**Comment by glouel** [comment]
@WebVeteran when you can, can you give a shot to this build, and try mirror mode again ? 

https://github.com/glouel/Aerial/releases/download/1.4.1test2/Aerial.saver.zip

Seems fixed here after a dozen hot corner tries, you'll still only get description on main screen but mirror work should always show on both now. Can you confirm ?

**Comment by WebVeteran** [comment]
Done. This is what I found, using only 4K videos...

**1.4.1 TEST2**
Mirrored: The same video plays on both. Very smooth. The title is only on the main screen.
Different: Frames being dropped (as expected).
Also, the fade effect only works on the main screen.

**1.4.1 BETA1**
If I click Preview the screens go blank. The system is unresponsive. I hear a beep. The desktop comes back on and the System Preferences are gone.
If I use a hot corner the screens go blank. Then grey apples appear, one on each screen.

**Comment by glouel** [comment]
> Done. This is what I found, using only 4K videos...
> 
> **1.4.1 TEST2**
> Mirrored: The same video plays on both. Very smooth. The title is only on the main screen.
🎉

> Also, the fade effect only works on the main screen.
Right. That I can probably fix

> **1.4.1 BETA1**
> If I click Preview the screens go blank. The system is unresponsive. I hear a beep. The desktop comes back on and the System Preferences are gone.
> If I use a hot corner the screens go blank. Then grey apples appear, one on each screen.
?!!

Sorry about that then. Everytime, independant of mirror etc ? Once is too much but that may help me narrow it down. Thanks for your feedback, hopefully I can fix that regression 😅

**Comment by WebVeteran** [comment]
> Sorry about that then. Everytime, independant of mirror etc ?

Yep. I even quit Prefs, reinstalled, etc. I figured it was Aerial crashing and the system picking the default apple screen saver.

**Comment by WebVeteran** [comment]
Fades and Titles worked in Test2. Sorry I can't help you!

**Comment by glouel** [comment]
Found it, I'll get a new build out soonish, will ping you back.

**Comment by glouel** [comment]
@WebVeteran took some time but here goes : 
https://github.com/glouel/Aerial/releases/download/1.4.1beta2rc1/Aerial.saver.zip

Should be fixed for you. The fade-in/out is also now showing on all screens. Not the descriptions. There are some new options including a same styled clock and ability to have a message on screen.

**Comment by WebVeteran** [comment]
That was b2.

b3...

Mirrored: still the same issue with the first frame being full brightness before the fade-in.
Different: Works as expected. Both screens fade from black. Lower framerate, but plays fine otherwise.

**Comment by glouel** [comment]
Again apologies about b2. 

Thanks for your report, that one is an easy fix, weird though I didn't see it on mojave but just saw it on 10.13 !

**Comment by glouel** [comment]
I fixed the flickering in this build : 
https://github.com/glouel/Aerial/releases/download/v1.4.1rc/Aerial.saver.zip

Thanks for catching that !

**Comment by WebVeteran** [comment]
Yes - fixed. Great work!

**Comment by glouel** [comment]
Closing as fixed with the release of 1.4.1
