### ISSUE TITLE
Feature Request: sync multiple computers screen savers

### ISSUE THREAD

**Issue by simneu** [JohnCoates/Aerial#783]
Hi,

First of all, thank you for the hard work on Aerial, great piece of software !

I have a pretty particular setup: 2 iMacs (one using the iMac screen + a secondary screen, the other using just the iMac screen). I can't use target display mode on one of the iMac (because target display mode is no longer supported on 5k iMacs) so I'm using Barrier, a fork of Synergy, to use the same mouse and keyboard for the two iMacs.

With barrier, I managed to launch the screensaver on both computers at the same time, but sadly they load each a random video, and I would love to have both synced up.

A possible solution might be to include the current timestamp into how the "random" video is selected.

What do you think ?

**Comment by glouel** [comment]
Hi @simneu 

Now that's a pretty particular setup you have... I use the swift library `shuffled()` right now to shuffle the the list of videos, it can be seeded. I'll see what I can do but I have no setup to test this. You'll have to give me feedback on builds :p

**Comment by simneu** [comment]
I could help testing of course !

Maybe another possible solution would be to be able to enter a "custom seed" (a string) used for the random. And if entered on both computers, you'll have the exact same "random" behaviour on both computers. That might be easier to test too, because not related to time.

Maybe there's cleaner ways to achieve this, that's what I can think for now. 😄

**Comment by glouel** [comment]
I just published beta5 with this : https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta5/Aerial.saver.zip

You need to explicitly enable "Synchronized mode" in video panel :

![Capture d’écran 2019-05-21 à 17 41 05](https://user-images.githubusercontent.com/37544189/58110362-aeb4de80-7bef-11e9-9eeb-5f15350f8b50.jpg)

I use the current number of minutes as a random seed, this should work 99.999% of the time and still give you a different sequence each time you launch Aerial (assuming a minute has elapsed since). Let me know how that goes.

**Comment by simneu** [comment]
Well, it works very nicely ! Thanks a lot, that was fast ! 😄
I still have a little "sync" issue (my main mac is starting the video like one second before the second mac) but that could come from multiple things and shouldn't be related to Aerial at all.

My second mac is older (no SSD), using wifi when first mac is using ethernet, and also has to wait for Barrier to send the "signal" to show the screen saver I guess. A bit of all of that could explain that it's not perfectly sync.

Thanks again, I'll stay available if you want to do more tests, and will report if I find issue using it.

**Comment by glouel** [comment]
Loading the video on a SSD will always start faster than a HDD, yes, not much I can do about that ;)

**Comment by glouel** [comment]
@simneu how long would you say the delay is on each screen, from the moment you go into the hot corner to the moment you see an image on each ?

The only hackish fix I could fix of would be to have something like wait for the next secondes%5==0 where secondes is at least 2 sec away, that could lead to a 5/7 sec starting delay (maybe 4 instead of 5 would work but still) with a black screen though. 

As of right now there's nothing in Aerial to do but I could add something like that to the mayyybe list ;)

**Comment by simneu** [comment]
@glouel The delay seems to depend on the video which is chosen. I've managed to have a synced launch on the "Africa Night", but having around 1sec of delay on "Approaching Burj Khalifa". Maybe it depends from the size of the video ?

I don't think this hackish fix is needed (because with this fix, that means the screen saver could start only when you're already away from the computers, which is sad).

**Comment by glouel** [comment]
> @glouel The delay seems to depend on the video which is chosen. I've managed to have a synced launch on the "Africa Night", but having around 1sec of delay on "Approaching Burj Khalifa". Maybe it depends from the size of the video ?

Yes it does, some files are much larger than others, there's an issue about this here : https://github.com/JohnCoates/Aerial/issues/780#issuecomment-493001466 

But that wasn't my question. My question was, time from hot corner to video on each screen ?

> I don't think this hackish fix is needed (because with this fix, that means the screen saver could start only when you're already away from the computers, which is sad).

I don't get what you mean here ? Maybe I wasn't clear about what I was proposing, I only proposed a slight synchronized delay when launching the screensaver on each machine, of a few seconds.

**Comment by glouel** [comment]
Closed as implemented with the release of 1.5.0
